global:
    frequencies: [30.0, 40.0, 95.0, 150.0, 220.0, 270.0]

BBMapParamCompSep:
    nside: 0

BBClEstimation:
    aposize_srcs: 0.1
    apotype_edges: 'C1'

BBREstimation:
    fsky: 0.1
    lmin: 30
    lmax: 200