global:
    bpw_edges: [2,30,50]
    beam_correct: True

BBMapsPreproc:
    purify_b: True

BBMaskPreproc:
    aposize_edges: 1.0
    aposize_srcs: 0.1
    apotype_edges: 'C1'
    apotype_srcs: 'C1'

BBPowerSpecter:
    pcl_code: 'NaMaster'

BBNullTester:
    compute_statistics: False

BBCovFeFe:
    analytic_covariance: False

BBCompSep:
    foreground_model: 'test/inputs/fg_model.yml'
