global:
    frequencies: [27,39,93,145,225,280]
    fsky: 0.1

BBMapParamCompSep:
    nside_patch: 0

BBClEstimation:
    aposize: 10.0
    apotype: 'C1'
    purify_b: True
    nlb: 10
    Cls_fiducial: './test_mapbased_param/Cls_Planck2018_lensed_scalar.fits'
    nside: 256

BBREstimation:
    lmin: 30
    lmax: 200
    r_input: 0.000
    nside: 256