global:
    frequencies: [30.0, 40.0, 95.0, 150.0, 220.0, 270.0]
    fsky: 0.1

BBMapParamCompSep:
    nside: 0

BBClEstimation:
    aposize: 10.0
    apotype: 'C1'
    purify_b: True
    nlb: 10
    Cls_fiducial: './Cls_Planck2018_lensed_scalar.fits'

BBrEstimation:
    lmin: 30
    lmax: 200
    r_input: 0.000