BBCompSep:
    # Sampler type (choose 'emcee', 'maximum_likelihood', 'single_point' or 'timing'
    sampler: 'maximum_likelihood'
    likelihood_type: 'h&l'
    pol_channels: ['E','B']
    l_min: 30
    l_max: 300

    cmb_model:
        cmb_templates: ["./examples/data/camb_lens_nobb.dat", 
                        "./examples/data/camb_lens_r1.dat"]
        params:
            r_tensor: ['r_tensor', 'tophat', [-10., 0., 10.]]
            A_lens: ['A_lens', 'tophat', [0., 1., "inf"]]

    fg_model:
        component_1:
            name: Dust
            sed: Dust
            cl:
                EE: ClPowerLaw
                BB: ClPowerLaw
                EB: ClPowerLaw
            sed_parameters:
                beta_d: ['beta_d', 'tophat', [0.1, 1.5, 10.]]
                temp_d: ['temp', 'fixed', [19.6]]
                nu0_d: ['nu0', 'fixed', [353.]]
            cl_parameters:
                EE:
                   amp_d_ee: ['amp', 'tophat', [0., 1., "inf"]]
                   alpha_d_ee: ['alpha', 'tophat', [-5., -0.5, 0.]]
                   l0_d_ee: ['ell0', 'fixed', [80.]]
                BB:
                   amp_d_bb: ['amp', 'tophat', [0., 1., "inf"]]
                   alpha_d_bb: ['alpha', 'tophat', [-5., -0.5, 0.]]
                   l0_d_bb: ['ell0', 'fixed', [80.]]
                EB:
                   amp_d_eb: ['amp', 'tophat', [-1.e3, 1., 1.e3]]
                   alpha_d_eb: ['alpha', 'tophat', [-5., -0.5, 0.]]
                   l0_d_eb: ['ell0', 'fixed', [80.]]
            cross:
                epsilon_ds: ['component_2', 'tophat', [-1., 0., 1.]]

        component_2:
            name: Synchrotron
            sed: Synchrotron
            cl:
                EE: ClPowerLaw
                BB: ClPowerLaw
                EB: ClPowerLaw
            sed_parameters:
                beta_s: ['beta_pl', 'tophat', [-10., -3., 0.]]
                nu0_s: ['nu0', 'fixed', [23.]]
            cl_parameters:
                EE:
                    amp_s_ee: ['amp', 'tophat', [0., 1., "inf"]]
                    alpha_s_ee: ['alpha', 'tophat', [-5., -0.5, 0.]]
                    l0_s_ee: ['ell0', 'fixed', [80.]]
                BB:
                    amp_s_bb: ['amp', 'tophat', [0., 1., "inf"]]
                    alpha_s_bb: ['alpha', 'tophat', [-5., -0.5, 0.]]
                    l0_s_bb: ['ell0', 'fixed', [80.]]
                EB:
                   amp_s_eb: ['amp', 'tophat', [-1.e3, 1., 1.e3]]
                   alpha_s_eb: ['alpha', 'tophat', [-5., -0.5, 0.]]
                   l0_s_eb: ['ell0', 'fixed', [80.]]

    systematics:
        bandpasses:
            bandpass_1:
                phase_nu: "./examples/data/phase_3layer_lf.txt"
                parameters:
                    shift_1: ['shift', 'Gaussian', [0., 0.03]]
                    gain_1: ['gain', 'Gaussian', [1., 0.03]]
                    angle_1: ['angle', 'Gaussian', [0., 0.1]]
                    dphi1_1: ['dphi1', 'Gaussian', [0., 2.]]
            bandpass_2:
                phase_nu: "./examples/data/phase_3layer_lf.txt"
                parameters:
                    shift_2: ['shift', 'Gaussian', [0., 0.03]]
                    gain_2: ['gain', 'Gaussian', [1., 0.03]]
                    angle_2: ['angle', 'Gaussian', [0., 0.1]]
                    dphi1_2: ['dphi1', 'Gaussian', [0., 2.]]
            bandpass_3:
                phase_nu: "./examples/data/phase_3layer_mf.txt"
                parameters:
                    shift_3: ['shift', 'Gaussian', [0., 0.03]]
                    gain_3: ['gain', 'Gaussian', [1., 0.03]]
                    angle_3: ['angle', 'Gaussian', [0., 0.1]]
                    dphi1_3: ['dphi1', 'Gaussian', [0., 2.]]
            bandpass_4:
                phase_nu: "./examples/data/phase_3layer_mf.txt"
                parameters:
                    shift_4: ['shift', 'Gaussian', [0., 0.03]]
                    gain_4: ['gain', 'Gaussian', [1., 0.03]]
                    angle_4: ['angle', 'Gaussian', [0., 0.1]]
                    dphi1_4: ['dphi1', 'Gaussian', [0., 2.]]
            bandpass_5:
                phase_nu: "./examples/data/phase_3layer_uhf.txt"
                parameters:
                    shift_5: ['shift', 'Gaussian', [0., 0.03]]
                    gain_5: ['gain', 'Gaussian', [1., 0.03]]
                    angle_5: ['angle', 'Gaussian', [0., 0.1]]
                    dphi1_5: ['dphi1', 'Gaussian', [0., 2.]]
            bandpass_6:
                phase_nu: "./examples/data/phase_3layer_uhf.txt"
                parameters:
                    shift_6: ['shift', 'Gaussian', [0., 0.03]]
                    gain_6: ['gain', 'Gaussian', [1., 0.03]]
                    angle_6: ['angle', 'Gaussian', [0., 0.1]]
                    dphi1_6: ['dphi1', 'Gaussian', [0., 2.]]
