name: continuous-integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install python dependencies
        run: |
          python -m pip install -U pip
          pip install -U numpy
          pip install -U healpy
          pip install -U pytest

      - name: Install BBPipe
        run: |
          python setup.py install --user

      - name: Unit tests
        run: |
          bbpipe test/test_ini.yml --python-cmd=python
          pytest -vv test/

      - name: Cache pip, brew
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.py }}-cache
          restore-keys: |
            ${{ runner.os }}-${{ matrix.py }}-cache
            ${{ runner.os }}-
